### ISSUE TITLE
Fine-tuned Flan-T5 release

### ISSUE THREAD

**Issue by SnowdenLee** [Yushi-Hu/tifa#1]
Hi, 

thanks for the amazing work. Could you maybe provide an estimated time for the fine-tuned Flan-T5 release?

Thanks a lot and looking forward to try it out!

**Comment by Yushi-Hu** [comment]
Thanks for your interest! We will release it in April.

**Comment by bigbrother001** [comment]
while, has the Fine-tuned Flan-T5 been released now?

**Comment by Yushi-Hu** [comment]
Sorry for the long wait! Eventually we decided to release a fine-tuned LLaMA 2 checkpoint: [https://huggingface.co/tifa-benchmark/llama2_tifa_question_generation](https://huggingface.co/tifa-benchmark/llama2_tifa_question_generation) . It works pretty well. Hope it is helpful!
