### ISSUE TITLE
what is the "ast_indexer" and how to change the path of it?

### ISSUE THREAD

**Issue by bigbrother001** [Yushi-Hu/tifa#2]
Thanks for your great work!
when I runing the code it will tell me 
`modelscope - INFO - Loading ast index from /home/nudt/.cache/modelscope/ast_indexer`

however, this path is not convenient for me, how can I make it load from the project directory?

**Comment by Yushi-Hu** [comment]
I think this is because of the cache directory of Modelscope. You can change it by setting the environment variable

export MODELSCOPE_CACHE = "[PATH YOU want]"

**Comment by bigbrother001** [comment]
Thanks very much!
